spring:
  name: cloud-vendor
  datasource:
    url: jdbc:h2:file:/data/rest-demo-db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    show-sql: true

  #JPA Settings
  jpa:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
  port: 8080
  address: 127.0.0.1

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem